spring.application.name=clientes-app
server.port=8090

spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:h2:mem:pruebaTecnica
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true


logging.level.root=INFO
logging.level.com.pruebatecnica.nttdata=DEBUG
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n